# Generated by Django 3.2.13 on 2022-06-20 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tcr_id', models.CharField(default='0', max_length=8)),
                ('ter_id', models.CharField(default='0', max_length=8)),
                ('tp_id', models.CharField(default='0', max_length=8)),
                ('log_location', models.CharField(max_length=50)),
                ('test_status', models.CharField(choices=[('P', 'PASS'), ('F', 'FAIL'), ('R', 'RUNNING'), ('T', 'TERMINATED'), ('I', 'TERMINATING'), ('U', 'Unknown')], max_length=1)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField()),
                ('run_type', models.CharField(choices=[('S', 'SINGLE'), ('B', 'BUCKET')], max_length=1)),
                ('error_message', models.TextField(default='', verbose_name='Error')),
                ('sp_name', models.CharField(max_length=50, verbose_name='Service Processor')),
                ('test_function', models.CharField(default='', max_length=30)),
                ('test_category', models.CharField(default='', max_length=30)),
                ('proc_id', models.IntegerField(default=0)),
                ('proc_hash', models.CharField(default='', max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
