# Generated by Django 3.2.13 on 2022-06-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hst_ct_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='user_id',
            new_name='user',
        ),
    ]
