# Generated by Django 3.2.13 on 2022-06-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hst_ct_app', '0003_alter_tests_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='job_id',
        ),
        migrations.AddField(
            model_name='tests',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tests',
            name='run_type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('BUCKET', 'Bucket')], default='SINGLE', max_length=6),
        ),
        migrations.AlterField(
            model_name='tests',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tests',
            name='test_status',
            field=models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('RUNNING', 'Running'), ('TERMINATED', 'Terminated'), ('TERMINATING', 'Terminating'), ('UNKNOWN', 'Unknown')], default='RUNNING', max_length=11),
        ),
    ]
