# Generated by Django 3.2.13 on 2022-11-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hst_ct_app', '0004_auto_20220622_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='log_location',
            field=models.CharField(max_length=500),
        ),
    ]
