# Generated by Django 3.2.13 on 2022-11-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hst_ct_app', '0005_alter_tests_log_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='error_message',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Error'),
        ),
    ]
